### PR TITLE
style: add card component

### PR DESCRIPTION
**Pull request by anik31**
In components folder card.css contains the css for the card components.

docs.html contains the html for all the components.

Deploy preview - https://deploy-preview-4--vacay-ui.netlify.app/docs

### CODE REVIEW

**Review by ParthParolekar — APPROVED** [review]
Everything looks great. The UI is clean too. Nice work! :+1:

**Review by VLeads — APPROVED** [review]
Everything is great. Go ahead !!

**Comment by anik31** [comment]
Thanks for reviewing @VLeads @ParthParolekar

**Comment by Anurag021** [comment]
Looks god to me

**Pull request merged**
